package hello.board;

public class ZZ_MEMO {
    /*
    검증
    board - id, writer, title, content, regdate, updatedate
    @notblank = notnull+하나의캐릭터이상
    @Size(max = 30) title
    @Size(max = 100) content
    @notblank title content
    member id, loginid, name, password
        @notblank name, loginid, password
        @size(max = 8) name, loginId
        @Size(min = 4, max = 12) password
        
    boardController write bindingResult 완료. 메시지 수정 v
    
    memberController editMember 작성중
    
    alert 띄우기 자바스크립트로 안됨. th:inline cddata 해야될듯

    multipart file 받아서, 이미지 확장자 체크후 저장후 출력.
    
    멀티파트파일 -> 컨트롤러에서 FileStore 호출 파일작성후 이름받아서 photo 객체 만들어 반환
    -> 이 photo 객체를 repo 에 저장 -> photo 객체를 board 에저장
    
    멀티파트파일 -> board 에 photo idlist 조회해서 이전 photo 삭제 후 -> 컨트롤러에서 FileStore 호출 파일작성후
    이름받아서 photo 객체 만들어 반환-> 이 photo 객체를 repo 에 저장  -> board 수정

    멀티파트파일 write 종료.

    멀티파트파일 update 종료.
    
    예외처리ㅡ 404페이지 등 종료.
    일단 1차종료.

     */
    //=====================================================================
    /*

    DB 통신

    참고) unique 고려해봤으나 앞에서 처리하고 notnull 로만

    테이블
    @board

    Long id;                    pk, autogenerated       bigint (8byte)
    String writer;              notnull size8           varchar(8)
    String title;               notnull, size30         varchar(30)
    String content;             notnull, size100        varchar(100)
    LocalDateTime regedate;     Datetime                Datetime
    LocalDateTime updateDate;   Datetime                Datetime

    List<Long> imageIds; -> @image 테이블 조인해서 사용

    create table board
(
id bigint not null auto_increment primary key,
writer varchar(8) not null,
title varchar(30) not null,
content varchar(100) not null,
regedate Datetime,
updateDate Datetime
);

    -> auto_increment 삭제하고 mybatis 에서 auto-genearated key 사용


    @member

    Long id;                    pk, auto                bigint
    String loginId;             unique max8
    String username;            unique max8
    String password;            notnull unique min4 max12

    loginId 와 username 둘다 unique + notnull 하고싶은데 방법을 모르겠음 없나?
            => 있음. 일단 workbench gui 로 했음.
            => 단순히 unique 추가가 아니고 uniqueIndex 생성하는 방식인듯
    일단 unique 만적용하고 notnull(notblank) 는 validation 에서 처리

    username = board.writer 이기 떄문에 unique 해야됨.

    create table member (
    id bigint not null auto_increment primary key,
    loginId varchar(8) not null,
    name varchar(8) not null,
    password varchar(12) not null
    );


    @image

    Long boardId                bigint
    Long imageId                bigint PK <- 일단 pk 용으로 만들긴 햇는데 안씀;
    String uploadImageName;     varchar(50)
    String storeImageName;      uuid varchar(41)  UUID 는 36자 + 확장자(5자) .webp 는 4글자니까?
    String imageAddress;        varchar(100)

    create table image (
    store_image_name varchar(36) primary key,
    upload_image_name varchar(50),
    image_address varchar(100),
    boardId bigint
    )

    현재 이미지를 저장 후 이미지의 주소를 board 에 list 로 저장하는 로직
    -> 이미지는 독립적으로 저장 후, image 테이블에 boardId 를 같이 저장해서 join 해서 조회 로 변경
    -> 일단 join 하지 말고 boardid 로 imagerepo boardrepo 따로 호출하자.


    @Comment

    Long commentId          bigint                  pk
    Long boardId            bigint                  fk(일단 적용X)
    String writer           varchar(8)  notnull
    String content          varchar(50) notnull
    LocalDateTime regDate   Datetime

    Long group_id           bigint                  댓글그룹id (모댓글id)
    Integer group_order     int                     댓글 순서 (0모 1~자)
    Integer group_depth     int                     댓글 깊이 (0모 1자)
    String target           varchar(8) notnull      답글 대상


    테이블작성완료
    맵퍼/테스트 작성완료
    main 띄움 -> 이미지에러

    전체로직수정 -> 일단 image 랑 board 저장및 read 방식 수정완료
    회원가입 중복loginId 처리 -> username 은 중복처리 하지말까? -> 해야됨
    중복 처리에 다소 오랜 시간이 소요됬음... 일단 잘됨
    메서드를 나눌까 합칠까 이벤트리스너를 나눌까 합칠까 더 고민이 필요함
    
    게시판 페이징 처리
    https://to-dy.tistory.com/90 참고
    write/update 시 currentPage 넘기는거 redirectDTO 에 currentPage 넣고
    get 은 reqParam post 는 modelattr 로 받아 DTO.currentPage 넣고 넘김
    
    조회수 처리
    일단 중복처리 없이 단순하게 구현하도록 한다.
    Board 에 viewCount 추가 db 에 default(0) 추가해서 save 시 코드변동 X

    검색기능
    https://m.blog.naver.com/lgr0406/221750526297 참고. Criteria 이용
    sql 은 itemdbservice 참고해서 작성했고, view 단은 해당 블로그 참고
    
        가장 오래걸리고 스트레스 많이받음. 뒤에 서버통신은 금방했는데 view <-> controller 간의 파라미터 전달에
        thymeleaf 에 대한 이해부족과 자바스크립트를 안쓰려는 마인드셋으로 인해 굉장히 애를 먹음.
        criteria 를 직접 받고 주는 형태도 꺼려서 더 어려웠던걸로 기억. 결국 쓰기로 결정
        결국 타임리프에서 td:data 로 넘어온값들 설정해서 읽기쉽게 해주고 form hidden input 에 넘어온 데이터들 저장
        javascript (jquery) 를 이용해 이벤트리스너 붙여 a -> (get)form.submit 으로 바꿔 전송으로 함.
        땜질하듯이 해놨고, 이로인해 인터셉터들 url 붙이는것도 전부 수정함. 나중에 문제생기면 고생할듯.
            ㄴ> request 객체 등 기본제공객체 들과 기본 기능들을 좀 더 활용하려는 마인드를 가져야할듯. 괜히 어렵게 뭐 만드려고
                하니까 더 복잡하고 어려워짐...
                
    부트스트랩 적용
    쉬울줄 알았는데 정말 난해하고 어려움
    프론트 예전에 한거 거의 다 까먹어서 그런거 같기도 하고 클래스 적용 줄임문 같은걸 잘 모르겠어서 그런듯
    nav-css 와 fragment.html 을 통해 네비게이션 html 부 및 스타일을 분리함
    nav-css 경로가 th:href 로 안하면 안되던거 기억. (상태코드 200 이정상)

    list 완료
    read 완료
    페이지네이션 액티브 색칠 완료
    writeForm 완료 ->  파일 미리보기 jquery 설정중 https://greatps1215.tistory.com/5 참고
    첨부파일 미리보기 완료

    editForm
        editForm 에서 문제가 생겼는데 이미지 업로드 후 수정시 이미지를 불러올수 없다는 것.
        input type=file 은 value(기본값) 을 설정할수 없다고 한다. 보안상

        수정방법 (내가 생각한거라 조잡할수도)
        writeForm 과 동일해 보이는 폼을 만들고, controller 에서 model 로 전달받은 원 이미지를 보여준다.
        마치 업로드 중인것 처럼 보이게 하고, 수정이 없는지 판단하여 없으면, DB 는 수정X
        수정이 있는데 빈칸인지 확인하여 DB 삭제, 수정이 있는데 파일이 바꼇으면 DB 수정 으로 한다.

            폼 만드는건 폼 자체의 크기를 줄이고 overflowhidden 으로 버튼부만 남겨 만듦. 옆에 span 박스 붙임(이름표시용)

        들어오는 이미지 갯수에 따라 이름 표시용 span 박스 내부내용 바꿔주면 모방은 끝남.
        현재 폼 모방은 다끝낫고, DB 단에서 "수정이 없으면 DB 수정X " 이부분 해야됨.
        아예 editform 에서 하나도 안건드리면 표시만 되고 업로드 상태가 안변함.
        index 같은거 하나 심어서 controller 에서 감지하게 할 예정

        하다가 loginController 에서 url 파라미터 제대로 처리 못하던거 수정함. 오래걸림.
        컨트롤러에서 redirect: 할때 한글 URLEncoder 로 인코딩 해야되는걸 꺠달음. 그럴거 같긴햇음
        현재 editform 의 onsubmit 부분 동작이 이상함. 수정해야함
        th:action 이 쿼리스트링 까지 붙여서 그대로 요청하는지는 잘모르겟음. 이게아니면 설명이 안되긴 함

        th:action 이 쿼리스트링까지 붙여서 action 속성 값 설정하는거 확인함
            => 검색시 파라미터 붙이며 개지랄 하던거 삭제함.
            
        일단 editform 완성한듯. 인터셉터 등 버그들도 수정했음

    loginForm

        간단하게 부트스트랩 쓰ㅣ움.
        th:error 로 메시지 내보내던거 부트스트랩 server side validation 넣었음. class=is-valid 랑 feedback
        추가로 세션에 isValidRequest 추가해서 로그인 해주세요 alert 고침
        HttpSession 이랑 Javascript sessionStorage 다른거란걸 앎.
        브라우저 내 저장소 cookie, HttpSession, webStorage(localStorage , sessionStorage) 이렇게 구분됨
            webStorage 는 html5 에서 도입된 저장소. 키 value 쌍으로 저장하고 서버전송 X 로컬에만 저장

        문제발견: 글 작성자여부 판별을 username 으로 하는데 문제는 username 이 변경가능하다
            변경 불가능한 값을 board 에 추가로 넣어줄 필요가 있다. username 은 변경되면 본인글 아니라고 뜸.
            따라서 member 테이블의 id 를 넣어주기로 한다.
        
        일단 끝

    member/addform
    
        유효성 검사를 다시 만들어야될듯 디자인은 얼추 됨
        유효성 검사 그냥 유지. 중복체크하는 ID 와 닉네임은 클라단에서. 스타일은 서버사이드 방식만 사용 (통신X, class is-valid)
        비밀번호는 서버단에서 -> 비번틀리면 화면 새로고침됨

        plain javascript 와 jqeury 간의 차이로 인해 사용하지 못하는 메서드들이나 값들이 있음.
        당장 javascript .add() 나 .checkvalidity() 같은거 jquery 에 없거나 달라서 사용이 안됨.
        이거 때문에 좀 당황한듯. 없거나 잘못되면 console에 메서드가 아니라고 나옴. (아마 정의되지 않아서)
        
    member/editform
    
        addform 과 거의 유사, 시작시 중복체크 true 만.
        
        
    댓글기능
    https://kuzuro.blogspot.com/2019/10/14.html 참고
    맵퍼 xml 까지 끝내고 repository 랑 test 작성해야

    repo test 끝내고 read.html 작성중 (controller 와 같이)

        댓글 결국 textarea 랑 placeholder 로 표시함 (폼태그는 없음) ul-li 로 했어야 하나 잘 모르겠음
        수정 버튼 누른 그자리에서 즉시 수정하려고 해당 방식을 사용
        댓글 수정은 ajax 로, 등록/삭제는 그냥 새로고침 되게 했음.
            등록/삭제 메시지 rttr 로 전송, 타임리프에서 해당 값 받아서 jquery 로 체크후 alert 함.

        validation 은 댓글 등록은 html validation,
        수정은 form 이 아니여서 글자수만 html valid 하고 required 널체크는 자바스크립트에서 함
            서버단에서는 validation 적용 일단 안함...

        $(this) 와 $(event.target) 의 차이 대충은 알겠는데 이벤트 전파에 따른 선택 에 차이인듯.  
            지금까진 target 썻는데 this 로 나중에 바꿀예정
        태그 내용 및 속성 같은거 좀 나중에 쳐내고 해야겠음.

        **** 위의 댓글처리를 하고 나서 느낀점
        1. 댓글 등록/삭제 시 페이지를 새로고침 -> url 변화 -> 기존의 queryString 이 날아감(다시 붙여야됨)
            특히 currentPage 뿐만 아니라 검생중일때 option, keyword 다날아가는거 고통
        2. 댓글 삭제시에는 replace 로 넘겨서 상관없지만, 등록시에는 단순히 컨트롤러에서 redirect -> 뒤로가기 하면 이전페이지 노출
        
        => 결국 댓글 등록 / 삭제 역시 ajax 로 진행해야 할듯
        
        ㅇ 1/4 오후
        ajax 요청 파라미터 - 컨트롤러 파라미터 받기 진행중
            serializeObject 등 시도해보았으나, 결국 String 과 serialize 한 쿼리스트링 형식 String 으로 퉁침.
            쿼리스트링 형식은 form-encoded 로 보내서 @ModelAttribute 로 받음
        ajax - 컨트롤러 처리부분은 됫고, 이제 컨트롤러에서 필요한 정보 리턴 후 폼 채워서 페이지 리로드 없애는 작업 진행중
        
        ㅇ 1/4 저녁
        댓글처리 완료
        수정중에 다른댓글 수정? - 치명적이진 않으니 보류
        
        ㅇ 1/11 오후
        board 삭제했을때 -> 댓글도 삭제되게 (수정은 변함없음)
        댓글 작성자 수정시 writer 수정 은 꼭 필요한가? 일단 보류
        
        답글기능 시작 -> comment 에 group_number(모댓글 번호), group_order(순서), group_depth(깊이) 추가, target 추가
        답글달기 other-comment-username.onclick 으로 other-comment 추가

        ㅇ 1/13 저녁
        답글 폼 달기 도저히 힘들어서 답글은 location.reload() 했음.
        일단 댓글관련 기능들 끝난듯.

        ㅇ 1/16 오후
        ck editor 적용중
            자바스크립트 불러오는 법 정확히. plainhtml / 타임리프 나눠서 다 가능. 인터셉터 체크 주의

            이미지 로컬에서 불러오는거 보안문제로 막힘 -> 브라우저 요청을 url 로 바꾸고 해당 url 을
                스프링 내에서 다시 로컬파일 요청으로 변환 (WebConfig 에 기입)

        ㅇ 1/18 오후
        이미지 업로드 진행중
            1. ckeditor 에서 파일 첨부를 하는 순간 storeFile.storeImage 에 의해 로컬에 파일이 write 된다.
                ㄴ 게시글을 쓰다가 취소하거나 사진을 수정해도 로컬에 파일이 그대로 잔류함.
            2. DB 로 이미지 id 를 통해 이미지를 관리하던게 무용지물이 됨

            일단 DB 에 ckeditor 삽입된 이미지 storename 을 통해 저장 후 DB 정보로 로컬파일 삭제
            storename 을 기반으로 이미지 업로드 및 수정 완료
            
            Git 설정 및 Github 에 push 완료 이제부터 필요없는 부분 쳐 낼 예정

        ㅇ 1/19 오후
            이미지 업로드 관련 필요없는 코드 제거
            controller /list 제거

                
              

            `



    
    카테고리화
    board 테이블에 카테고리 필드 추가하고, 쿼리스트링으로 카테고리 넘기기?
    
     */

    /**
     * 보류된 기능 (치명적이지 않은 경우)
     *
     * 첨부파일 다운로드 -> 해야될듯
     * 파이어베이스(웹DB)에 이미지 저장
     * 소셜로그인
     * 관리자페이지
     *
     * 공공데이터 포털 API?
     *
     * ====================================
     * member 의 username 변경 시 board 와 comment 의 writer 변경 (db update cascade)
     *
     * =====================================
     * 댓글 수정 중, 다른 댓글 수정(버튼누름) -> 처리함
     */


    /* 몰라 미래를 위해
     * list 페이징 처리
     * 글 검색 기능
     * 댓글
     * AOP 보안기능?
     * 로그인, 회원관리
     *
     * 기저지식, http프로토콜 동작방식
     * 서블릿, jsp 활용 , 스프링의 핵심
     */

}
